### ISSUE TITLE
I will ask you to moderate this statement

### ISSUE THREAD

**Issue by bres55** [ForrestFire0/GenericBMSArduino#2]
I will ask you to moderate this statement.

"Another Smart BMS Reader that I found to be really bloated and not at all conforming to the traditional arduino library style (it isnt even a library."

"Bloated" is a word, I feel, is an unnecessary critism. 
The program was kept simple for a reason. To allow others to see how to access the BMS, and use this information. It was presented, to allow others, (people, like yourself,) to take it further. I made it clear when I posted it, I had taken it as far as I wished to take it, in that form. I have used a bespoke variation of it without a hitch for over 2 years now, and I am able to remotely, turn off and on the balancing, and the mosfets, if/when required. It suited my project, and I was happy to share that information.

GitHub Community Guidelines
Respect each other. Nothing sabotages healthy conversation like rudeness. Be civil and professional, and don’t post anything that a reasonable person would consider offensive, abusive, or hate speech. Don’t harass or grief anyone. Treat each other with dignity and consideration in all interactions.

**Comment by ForrestFire0** [comment]
Sorry you felt this way - I updated the readme with a more accurate description of my opinion.
