### ISSUE TITLE
Reading error for currents >2,56A

### ISSUE THREAD

**Issue by silviocross** [ForrestFire0/GenericBMSArduino#6]
Hi, thank you for the wonderful and clear library.
I made a small modification in the pack current reading in order to get proper and signed values:

`int16_t temp;` instead of `uint16_t temp;`

I am using 16S and 3 NTCs, so the data size of the cell data response (0x04) is normally 32, while the size of the pack data response (0x03) is normally 38.
unfortunately I get an error when the currents rise over 2,56A (FF FF): the size of cell data is becoming 38 and no answer is coming from the 0x03 message. 

can you please provide some support?
thank you
Silvio

**Comment by ForrestFire0** [comment]
Hello,

It is hard to debug your board remotely. I have a few suggestions, however.

1. Try turning on debug mode by editing line 16 in BMS.h (turn false to true). This should print out lots of information, including the hex responses from all of the requests.
1. Something isn't right with your math. If you are correct with it being a signed integer, then the maximum value of a signed two byte integer is 2^15 or 32768. Divide by 100 and that corresponds to 327.68 amps.

Run the code with debug mode enabled and post the serial monitor output - I'll see what can be gathered from that.

You said the problem occurs when the amps are high... what is your load? Motors are known to generate nasty electric fields that sometimes interfere with data transmission... although at 9600 baud you should be good. Maybe not at 327 amps lol.

Thank you for your kind message!

**Comment by silviocross** [comment]
I was finally able to sort out the issue from the "electrical" point of view:

- Shielded cable with twisted pairs
- Galvanic isolation in the serial connection path between BMS and ESP32

It works!

**Comment by ForrestFire0** [comment]
Awesome! Lesson learned about high currents...

**Comment by ForrestFire0** [comment]
Awesome! Lesson learned about high currents...
